import bcrypt from 'bcrypt';
import prisma from '../../prisma/client';
import type { CreateFacultyInput, UpdateFacultyInput } from './faculty.validation';

/**
 * Auto-generates an unchangeable sequential Employee ID / Faculty ID.
 * Format: [Year][DeptCode]FAC[Sequential 3-digit number]
 * Examples:
 * - 1st CS Faculty -> 2026CSFAC001
 * - 2nd CS Faculty -> 2026CSFAC002
 * - 1st EE Faculty -> 2026EEFAC001
 */
export const generateNextEmployeeId = async (departmentId?: string): Promise<string> => {
  const currentYear = new Date().getFullYear();
  let deptCode = 'FAC';

  if (departmentId) {
    const dept = await prisma.department.findUnique({ where: { id: departmentId } });
    if (dept?.code) {
      deptCode = dept.code.toUpperCase().trim();
      if (deptCode === 'CSE') deptCode = 'CS';
      if (deptCode === 'ECE') deptCode = 'EC';
      deptCode = `${deptCode}FAC`;
    }
  }

  const prefix = `${currentYear}${deptCode}`;

  const existingFaculties = await prisma.faculty.findMany({
    where: {
      employeeId: {
        startsWith: prefix,
      },
    },
    select: { employeeId: true },
  });

  let maxSeq = 0;
  for (const f of existingFaculties) {
    const match = f.employeeId.match(new RegExp(`^${prefix}(\\d+)$`));
    if (match) {
      const seqNum = parseInt(match[1], 10);
      if (seqNum > maxSeq) {
        maxSeq = seqNum;
      }
    }
  }

  const nextSeq = maxSeq + 1;
  return `${prefix}${String(nextSeq).padStart(3, '0')}`;
};

export const getFaculties = async () => {
  return prisma.faculty.findMany({
    include: {
      department: true,
    },
    orderBy: { employeeId: 'asc' },
  });
};

export const getFacultyById = async (id: string) => {
  return prisma.faculty.findUnique({
    where: { id },
    include: { department: true },
  });
};

export const createFaculty = async (data: CreateFacultyInput) => {
  const firstName = data.firstName || data.fullName?.split(' ')[0] || 'Faculty';
  const lastName = data.lastName || data.fullName?.split(' ').slice(1).join(' ') || '';

  let deptId = data.departmentId;
  if (deptId) {
    const deptExists = await prisma.department.findUnique({ where: { id: deptId } });
    if (!deptExists) {
      const firstDept = await prisma.department.findFirst();
      if (firstDept) {
        deptId = firstDept.id;
      } else {
        const newDept = await prisma.department.create({
          data: { name: 'Computer Science & Engineering', code: 'CSE' },
        });
        deptId = newDept.id;
      }
    }
  } else {
    const firstDept = await prisma.department.findFirst();
    deptId = firstDept
      ? firstDept.id
      : (
          await prisma.department.create({
            data: { name: 'Computer Science & Engineering', code: 'CSE' },
          })
        ).id;
  }

  // Verify email uniqueness
  const existingFaculty = await prisma.faculty.findUnique({
    where: { email: data.email },
  });

  if (existingFaculty) {
    throw new Error(`A faculty member with email '${data.email}' already exists in the system (Employee ID: ${existingFaculty.employeeId}).`);
  }

  // Force unchangeable auto-generated Employee ID
  const autoGeneratedEmployeeId = await generateNextEmployeeId(deptId);

  const hashedPassword = await bcrypt.hash('admin123', 10);
  await prisma.user.upsert({
    where: { email: data.email },
    update: {
      fullName: `${firstName} ${lastName}`.trim(),
    },
    create: {
      fullName: `${firstName} ${lastName}`.trim(),
      email: data.email,
      password: hashedPassword,
      role: 'FACULTY',
    },
  });

  return prisma.faculty.create({
    data: {
      firstName,
      lastName,
      email: data.email,
      employeeId: autoGeneratedEmployeeId,
      phone: data.phone || 'N/A',
      designation: data.designation || 'Professor',
      qualification: data.qualification || 'Ph.D.',
      specialization: data.specialization || 'General',
      joiningDate: data.joiningDate || new Date().toISOString().split('T')[0],
      status: data.status || 'ACTIVE',
      departmentId: deptId,
    },
    include: { department: true },
  });
};

export const updateFaculty = async (id: string, data: UpdateFacultyInput) => {
  // Omit employeeId from updates to make it permanently locked
  const { employeeId, ...updateFields } = data as any;

  return prisma.faculty.update({
    where: { id },
    data: updateFields,
    include: { department: true },
  });
};

export const deleteFaculty = async (id: string) => {
  const faculty = await prisma.faculty.findUnique({ where: { id } });
  if (!faculty) return null;

  // Clean up user account if linked
  if (faculty.email) {
    await prisma.user.deleteMany({
      where: { email: faculty.email, role: 'FACULTY' },
    }).catch(() => {});
  }

  return prisma.faculty.delete({ where: { id } });
};
