import { useState } from 'react';
import { FileText, Sparkles, Download, CheckCircle2 } from 'lucide-react';

export const AIReportGenerator = () => {
  const [reportType, setReportType] = useState('Monthly Attendance Summary');
  const [format, setFormat] = useState('PDF');
  const [generatedReport, setGeneratedReport] = useState<string | null>(null);

  const handleGenerate = () => {
    setGeneratedReport(
      `📊 EXECUTIVE INSTITUTIONAL REPORT: ${reportType.toUpperCase()}\n` +
      `Generated by AI ERP Analytics Engine • Date: ${new Date().toLocaleDateString()}\n` +
      `--------------------------------------------------------------------------------\n\n` +
      `1. OVERVIEW & EXPLICIT METRICS:\n` +
      `   • Total Enrolled Students: 1,200 Across 6 Academic Departments\n` +
      `   • Average Campus Attendance Rate: 88.4%\n` +
      `   • Total Tuition Fee Collected: ₹1,22,00,000 (91.5% Target Achieved)\n` +
      `   • Active Faculty Roster: 85 Full-time Members\n\n` +
      `2. KEY ACADEMIC HIGHLIGHTS:\n` +
      `   • Computer Science & Engineering achieved highest attendance (92.1%).\n` +
      `   • Electrical Engineering fee collections reached 94% on schedule.\n` +
      `   • Semester 5 DBMS course flagged for minor attendance drop (82%); faculty notified.\n\n` +
      `3. RECOMMENDATIONS FOR DEAN & ADMINISTRATORS:\n` +
      `   • Issue fee reminder notices for 85 pending student accounts prior to 15 October.\n` +
      `   • Conduct academic counseling for Semester 5 IT students.\n`
    );
  };

  const handleDownload = () => {
    if (!generatedReport) return;

    if (format === 'PDF') {
      const printWindow = window.open('', '_blank');
      if (!printWindow) return;
      printWindow.document.write(`
        <html>
          <head>
            <title>${reportType}</title>
            <style>
              body { font-family: monospace; padding: 30px; white-space: pre-wrap; background: #0f172a; color: #fde68a; }
            </style>
          </head>
          <body>${generatedReport}<script>window.onload=function(){window.print();}</script></body>
        </html>
      `);
      printWindow.document.close();
    } else {
      const blob = new Blob([generatedReport], { type: format === 'CSV' ? 'text/csv' : 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `Executive_Report_${reportType.replace(/\s+/g, '_')}.${format.toLowerCase()}`;
      a.click();
      URL.revokeObjectURL(url);
    }
  };

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <div>
        <h1 className="text-2xl font-black text-stone-900 dark:text-white flex items-center gap-2 font-['Outfit']">
          <FileText className="h-7 w-7 text-amber-600 dark:text-amber-400" />
          AI Executive Report Generator
        </h1>
        <p className="text-xs font-semibold text-stone-500 dark:text-stone-400 mt-1">
          Automated creation of comprehensive attendance, performance, and financial summaries
        </p>
      </div>

      <div className="rounded-3xl border border-amber-200/80 bg-white p-6 shadow-sm dark:border-stone-800 dark:bg-stone-900 space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="block text-xs font-extrabold uppercase tracking-wider text-stone-700 dark:text-stone-300 mb-1.5">
              Report Category
            </label>
            <select
              value={reportType}
              onChange={(e) => setReportType(e.target.value)}
              className="w-full rounded-2xl border border-amber-200 bg-amber-50/40 px-4 py-2.5 text-xs font-bold text-stone-900 focus:border-amber-500 focus:outline-none dark:border-stone-700 dark:bg-stone-800 dark:text-white"
            >
              <option value="Monthly Attendance Summary">Monthly Attendance Summary</option>
              <option value="Faculty Workload & Performance">Faculty Workload & Performance</option>
              <option value="Department Performance Matrix">Department Performance Matrix</option>
              <option value="Fee Collection & Dues Report">Fee Collection & Dues Report</option>
            </select>
          </div>

          <div>
            <label className="block text-xs font-extrabold uppercase tracking-wider text-stone-700 dark:text-stone-300 mb-1.5">
              Export Format
            </label>
            <select
              value={format}
              onChange={(e) => setFormat(e.target.value)}
              className="w-full rounded-2xl border border-amber-200 bg-amber-50/40 px-4 py-2.5 text-xs font-bold text-stone-900 focus:border-amber-500 focus:outline-none dark:border-stone-700 dark:bg-stone-800 dark:text-white"
            >
              <option value="PDF">PDF Report Document</option>
              <option value="CSV">CSV Data Spreadsheet</option>
              <option value="MARKDOWN">Markdown Summary</option>
            </select>
          </div>
        </div>

        <div className="flex items-center justify-end pt-2">
          <button
            onClick={handleGenerate}
            className="inline-flex items-center gap-2 rounded-2xl bg-gradient-to-r from-amber-500 via-orange-500 to-rose-500 px-6 py-3 text-xs font-black text-white shadow-lg shadow-orange-500/25 hover:shadow-orange-500/40 transition-all cursor-pointer"
          >
            <Sparkles className="h-4 w-4 text-yellow-200" />
            Compile AI Report
          </button>
        </div>
      </div>

      {generatedReport && (
        <div className="rounded-3xl border border-amber-200/80 bg-white p-6 shadow-sm dark:border-stone-800 dark:bg-stone-900 space-y-4">
          <div className="flex items-center justify-between pb-3 border-b border-amber-100 dark:border-stone-800">
            <span className="text-xs font-black text-emerald-600 dark:text-emerald-400 flex items-center gap-1.5">
              <CheckCircle2 className="h-4 w-4" /> AI Report Generated
            </span>
            <button
              onClick={handleDownload}
              className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-amber-500 hover:bg-amber-600 text-white text-xs font-black shadow-md cursor-pointer transition-colors"
            >
              <Download className="h-3.5 w-3.5" /> Download {format}
            </button>
          </div>
          <pre className="p-4 rounded-2xl bg-stone-900 text-amber-100 text-xs font-mono whitespace-pre-wrap leading-relaxed overflow-x-auto">
            {generatedReport}
          </pre>
        </div>
      )}
    </div>
  );
};

export default AIReportGenerator;
